name: Release to GHR
on:
  push:
    branches:
      - develop
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - uses: rui314/setup-mold@v1
        if: runner.os == 'Linux'
        with:
          make-default: true

      - name: Install Rust toolchain (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run:
          curl https://sh.rustup.rs -sSf | sh -s -- --profile default --default-toolchain stable -y

      - name: Cache cargo registry and build outputs
        uses: actions/cache@9a6a4f6079716b44e70b2e883cfdd6fb7d6ff5d9
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/bin
            target
          key: linux-cargo-stable-${{ hashFiles('Cargo.lock') }}

      - name: Install semantic-release-rust
        uses: baptiste0928/cargo-install@v1
        with:
          crate: semantic-release-rust
          version: "1.0.0-alpha.8"

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - name: Build x86 linux binary
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target x86_64-unknown-linux-gnu

      - name: Copy targets
        run: |
          mkdir dist
          mv target/x86_64-unknown-linux-gnu/release/katbin dist/katbin-x86_64-unknown-linux-gnu

      - name: Release
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENVIRONMENT: ${{ github.ref }}
          GHR: true
        run: npx semantic-release
